spring.application.name=playground
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/playground
spring.datasource.username=brian
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true